export interface PtwWrite {
    spotName: string,
    price: string,
    workStart: string,
    workEnd: string,
    wonch: string,
    super: string,
    workCompany: string,
    writer: string,
    writeDate: string,
    confirm: object | string,
    confirmType: object | string,
    confirmDate: object | string,
    workDate: string,
    workSpot: string,
    dangerType: string,
    workContent: string,
    workPeople: string,
    workResponse: string,
    dengerContent: string,
    disastarType: string,
    down: string,
}

export const ptwWrite = [
    {
        spotName: '세종시 블록형 단독주택공사',
        price: '57,247,729,000',
        workStart: '2020-11-30',
        workEnd: '2020-03-17',
        wonch: '(주)원청사',
        super: '(주)감리사',
        workCompany: '(주)지에스아이엘',
        writer: '이상범',
        writeDate: '2022-08-08',
        confirm: ['이상범','정대현','이은주','이정우'],
        confirmType: ['승인','미승인','반려','승인'],
        confirmDate: ['06.04 15:26','06.05 15:26','06.06 15:26','06.08 15:26'],
        workDate: '2022-08-09',
        workSpot: '방음터널 상부',
        dangerType: '고소 작업(높이 2m 이상)',
        workContent: '상부 방음판 교체',
        workPeople: '신호수1명, 유도원2명, 보통인부 5명',
        workResponse: '구범수',
        dengerContent: '차량운행 경로 미지정으로 인한 차량충돌 사고',
        disastarType: '추락,협착',
        down: '차량 운행 경로에 유도원 2명이상 배치. 지게차 이동 동선에 자재 적재, 터 작업 등의 확인 점검'
    }
]